version: '3.8'

services:
  selenium-tests:
    build: .
    container_name: qanova-tests
    environment:
      - BROWSER=chrome
      - HEADLESS=true
      - BASE_URL=https://www.google.com
      - TZ=America/Santiago
    volumes:
      - ./test-reports:/app/build/reports
      - ./screenshots:/app/build/screenshots
    networks:
      - qanova-network

  # Si necesitas Selenium Grid
  selenium-hub:
    image: seleniarm/hub:4.16.1-20240130
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - qanova-network

  chrome-node:
    image: seleniarm/node-chromium:4.16.1-20240130
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - qanova-network

networks:
  qanova-network:
    driver: bridge

volumes:
  test-reports:
  screenshots: