apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qanova-tests-ingress
  namespace: qanova-tests
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tests.qanova.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qanova-tests-service
                port:
                  number: 80